<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      const pro1 = new Promise((resolve, reject) => {
        throw 1;
      });
      const pro2 = pro1.then(
        (res) => res * 2,
        (err) => err * 3
      ); //这个pro2是第一个then函数调用得到的。和下面的catch函数属于不同的作业队列
      pro1.catch((err) => {
        err * 2;
      }); //和上面的then函数无关，不存在覆盖之类的情况
      pro2.then(
        (res) => console.log(res * 2),
        (err) => console.log(err * 3)
      ); //1*3*2=6
      //前面的结果是后面已决状态的数据
    </script>
  </body>
</html>
