# Promise 的基本使用

es6新增Promise这个api来处理异步场景。

Promise这个api并不能消除回调。只是让回调函数形成一个特定的模式，不要那么乱

```js
// Promise的语法如下：
const pro = new Promise((resolve, reject) => {
  //整个对象表示Promise的整个状态。回调函数表示未决阶段事情的处理（将未决状态推向已决状态）
  //通过调用resolve函数将Promise推向已决阶段的resolved状态
  //通过调用reject函数将Promise推向已决阶段的rejected状态
  //resolve和reject均可以传递最多一个参数，表示推向状态的数据
  //该阶段的处理函数是同步的，会立即执行
});
pro.then(
  (data) => {
    //这是thenable函数，如果当前的Promise已经是resolved状态，该函数会立即执行
    //如果当前是未决阶段，则会加入作业队列，等待到达resolved状态后执行
    //data为状态数据
  },
  (err) => {
    //这是catchable函数，如果当前的Promise已经是rejected状态，该函数会立即执行
    //如果当前是未决阶段，则会加入到作业队列，等待到达rekected状态后执行
    //err为状态数据
  }
);
```

**细节**

1. 未决阶段的处理函数是同步的，会立即执行
2. thenable 和 catchable 函数是异步的，就算是立即执行，也会加入到事件队列中等待执行，并且，加入的队列是微队列
3. pro.then 可以只添加 thenable 函数，通过pro.catch 可以单独添加 catchable 函数
4. 在未决阶段的处理函数中，如果发现!未捕获的错误，会将状态推向 rejected，并会被 catchable 捕获
5. 一旦状态推向了已决阶段，无法再对状态做任何更改
6. **Promise 并没有消除回调，只是让回调变得可控**

<img src="4.png" />

> 作业队列适用于对一个事件队列的多种处理

```js
//学习Promise的使用

function biaobai(god) {
  return new Promise((resolve, reject) => {
    //处理整个未决阶段的事情
    console.log(`邓哥向${god}发出了表白短信`);
    setTimeout(() => {
      if (Math.random() < 0.1) {
        //女神同意了。推向resolve状态
        resolve(true);
      } else {
        resolve(false);
      }
    }, 3000);
  });
}
const pro = biaobai("女神1");
console.log(pro); //对象中的PromiseState属性表示事情的三种状态：pending、resolved/fullfilled、rejected
pro.then((data) => {
  console.log(data); //女神的回应结果
});

//ajax相关：见test2.html

const pro = new Promise((resolve, reject) => {
  //未决阶段的代码会立即执行。只负责推向已决状态
  console.log("未决阶段");
  // resolve(123); //同步代码。立即就从未决阶段推向已决阶段了
  setTimeout(() => {
    if(Math.random()<0.3){
      resolve(123);
    }else{
      reject(new Error("发生错误"))
    }
  }, 3000);
});
pro.then(
  //pro对象到达已决阶段后会立即执行回调中的代码。只负责后续处理
  (data) => {
    console.log(data); //已决阶段的resolved状态
  },
  (err) => {
    console.log(err); //已决阶段的rejected状态
  }
);
pro.then((data2) => {
  console.log(data2);
}); //多个作业队列的注册

const pro = new Promise((resolve, reject) => {
  //未决阶段的函数是同步的，会立即执行
  console.log("a");
  resolve(1);//微队列
  setTimeout(() => {
    console.log("b");
  }, 0);//宏队列
});
pro.then(
  (data) => {
    console.log(data);
  } //这里的thenable函数和catchable函数是异步的。就算事情到了已决阶段也要加入到事件队列中等待执行栈留空
);
console.log("c"); // a c 1 b

const pro = new Promise((resolve, reject) => {
  throw new Error("123"); //pro:rejected。未决阶段的错误会导致pro的状态变成rejected
  reject(2); //无效。状态不可逆
  resolve(3); //无效。状态不可逆
     
});
pro.then((data) => {
  console.log(data);
});
pro.catch((err) => {
  console.log(err);
});
```
